// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDz7ypiws73PjAelWA9fROuvz2XGZnQDE',
    appId: '1:296067030491:web:2a6921f682a4fb2b431bfe',
    messagingSenderId: '296067030491',
    projectId: 'e-commerce-flutter-project-dev',
    authDomain: 'e-commerce-flutter-project-dev.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-project-dev.firebasestorage.app',
    measurementId: 'G-LPCZBQ507X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpDtcQNDH2sgsjT-89CHrVpA55Wj4klNU',
    appId: '1:296067030491:android:123fecda1aa1d5d8431bfe',
    messagingSenderId: '296067030491',
    projectId: 'e-commerce-flutter-project-dev',
    storageBucket: 'e-commerce-flutter-project-dev.firebasestorage.app',
  );
}
