// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnR6NbseWnZM3DbVgF0pEPsI8cbKzm6p0',
    appId: '1:473958023495:web:dc6901f9725fb1fb2d4c62',
    messagingSenderId: '473958023495',
    projectId: 'e-commerce-flutter-proje-f9f4a',
    authDomain: 'e-commerce-flutter-proje-f9f4a.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-proje-f9f4a.firebasestorage.app',
    measurementId: 'G-6EBE2QK2W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDMaXZuncla5Y4HuwbAMsr-q5wI2Xg88',
    appId: '1:473958023495:android:8ab3f9f1bcce8bfa2d4c62',
    messagingSenderId: '473958023495',
    projectId: 'e-commerce-flutter-proje-f9f4a',
    storageBucket: 'e-commerce-flutter-proje-f9f4a.firebasestorage.app',
  );
}
