default_platform(:android)

platform :android do
  desc "Build Flutter APK and upload to Firebase App Distribution"
  lane :firebase_distribution do
    branch = ENV["GITHUB_REF_NAME"] || "development"
    flavor = branch == "main" ? "production" : "development"

    sh "flutter clean"
    sh "flutter build apk --release --flavor #{flavor} -t lib/main_#{flavor}.dart --no-tree-shake-icons"

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      testers: "s.husain_10@hotmail.com, tester2@gmail.com",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      apk_path: "../build/app/outputs/flutter-apk/app-#{flavor}-release.apk",
      release_notes: "Automated build from #{branch} branch"
    )
  end
end